[build]
  command = "npm run build"
  publish = "dist"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Permissions-Policy = "camera=(), microphone=(), geolocation=(), payment=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https:; script-src-elem 'self' 'unsafe-inline' https:; style-src 'self' 'unsafe-inline' https:; font-src 'self' https: data:; img-src 'self' data: https: blob:; frame-src https:; connect-src 'self' https:; object-src 'none'; base-uri 'self'; form-action 'self' https:; upgrade-insecure-requests;"
    X-Robots-Tag = "index, follow"

[[redirects]]
  from = "/pay/*"
  to = "https://www.convergepay.com/hosted-payments/?ssl_txn_auth_token=DeOLn82%2FSEa6eKobnVJrFQAAAZ%2FuCOSW#!/payment-method"
  status = 302
